version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:12.0.0
        environment:
          DB_URI: mongodb://root:root@localhost:27017
      - image: circleci/mongo:4.4
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
    steps:
      - checkout
      - run: 
          "name": "Install dependencies"
          "command":  "npm install"
      - run:
          "name": "Run tests"
          "command": "npm test"